fix compile log

diff --git a/bin/dog b/bin/dog
--- a/bin/dog
+++ b/bin/dog
@@ -33,8 +33,8 @@ function compile_unwatch {
 
 function compile {
     echo 'compile'
-    rm -rf lib/*
     ${COFFEE} -o lib -c src
+    [[ $? > 0 ]] && echo 'compile error' && exit 1
     echo 'compiled'
 }
 
